services:
  web:
    build: .
    image: financial_assistant
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./chroma_db:/app/chroma_db
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - ollama

  
  db:
    image: postgres:17
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A finance worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - ollama

  celery-beat:
    build: .
    command: celery -A finance beat -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama


volumes:
  postgres_data:
  ollama_data: