# Generated by Django 5.2.4 on 2026-06-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_category_id_alter_expense_id_alter_income_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Category',
            new_name='category',
        ),
    ]
